mod 'puppet/nginx', '1.0.0'
mod 'puppetlabs/stdlib' 
mod 'puppetlabs/concat' 
mod 'puppetlabs/translate' 
mod 'puppetlabs-apt'
mod 'puppetlabs/docker'
mod 'samuelson/dockeragent'
mod 'jcustenborder-confluent', '4.0.55'
